package com.company.app.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * This class maps the company_info table into Java. 
 * This class was auto-generated by Hibernate tools.
 * @Id@GenratedValue and updatable propertiese were
 * updated.
 * 
 * Sample CompanyInfo JSON:
 * {
 *    "name" : "Company E",
 *     "email": "abc@def.com",
 *     "phone":"613-987-7654",
 *     "address":{
 *         "address":"999 Vicious Circle",
 *         "city":"Seattle",
 *         "country":"USA"
 *     },
 *     "beneficialOwners":[
 *         { "firstName":"Ben",
 *         "lastName":"Saini"},
 *          { "firstName":"Test",
 *         "lastName":"Test"}
 *     ]
 * }
 * 
 */
@Entity
@Table(name = "company_info", schema = "public")
public class CompanyInfo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int companyId;
	private Address address;
	private String name;
	private String email;
	private String phone;
	private Set<BeneficialOwner> beneficialOwners = new HashSet<BeneficialOwner>(
			0);

	public CompanyInfo() {
	}

	public CompanyInfo(int companyId, Address address, String name) {
		this.companyId = companyId;
		this.address = address;
		this.name = name;
	}

	public CompanyInfo(int companyId, Address address, String name,
			String email, String phone, Set<BeneficialOwner> beneficialOwners) {
		this.companyId = companyId;
		this.address = address;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.beneficialOwners = beneficialOwners;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "company_id", unique = true, nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "add_id", nullable = false, insertable = true, updatable = true)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "name", unique=true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinTable(name = "company_info_owner", schema = "public", joinColumns = { @JoinColumn(name = "company_id", nullable = false, updatable = false, insertable=true) }, inverseJoinColumns = { @JoinColumn(name = "owner_id", nullable = false, updatable = false, insertable = true) })
	public Set<BeneficialOwner> getBeneficialOwners() {
		return this.beneficialOwners;
	}

	public void setBeneficialOwners(Set<BeneficialOwner> beneficialOwners) {
		this.beneficialOwners = beneficialOwners;
	}

}
